---
title: Johnylab's Johnyplate
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Sections (n√£o alterar)
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
description: My own Jekyll-Babel boilerplate.
baseurl: "/johnyplate"
url: http://johnylab.net
markdown: kramdown
sass:
  style: compressed
exclude:
- node_modules
- desktop.ini
- gulpfile.js
- npm-debug.log
- package.json
